[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci || npm install", "cd client && npm ci || npm install"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "npm run start"
